name: Test

on:
  push:
  pull_request:

jobs:
  UnitTest:
    name: Unit Tests

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: [7.0, 7.1, 7.2, 7.3, 7.4]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - if: matrix.php-version == '7.0'
      name: Setup PHP 7.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mcrypt
        coverage: xdebug

    - if: matrix.php-version > '7.0'
      name: Setup PHP > 7.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Show PHP Info
      run: php -v && php -r "foreach (get_loaded_extensions() as \$each) echo \$each.':'.phpversion(\$each).PHP_EOL;"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --ignore-platform-reqs
      
    - name: Run Unit Tests
      run: composer run-script test -- --coverage-clover coverage.xml
      env:
        RUN_DB_TEST: YES
        PGSQL_DSN: pgsql:host=localhost;port=5432;dbname=postgres
        PGSQL_USER: postgres
        PGSQL_PASSWORD: postgres

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        files: ./coverage.xml