name: Test

on:
  push:
  pull_request:

jobs:
  UnitTest:
    name: Unit Tests
    
    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --ignore-platform-reqs
      
    - name: Run Unit Tests
      run: composer run-script test
